In [3]:
import numpy as np

In [79]:
def my_calculate_doa(TDOAs,soundSpeed,chanSpacing):
    # minimum and maximum values that arcsin can accept.. force values to be between these
    max_val = 1
    min_val = -1
    #dist = np.array([[0,0,0,0],[1,0,0,0],[2,1,0,0],[3,2,1,0]])

    #dists = dist.flatten()
    #unique_pairs = np.where(dists > 0)[0]


    #unique_dists = dists[unique_pairs]
    #tdoas = TDOA.flatten()[unique_pairs]

    #print(unique_dists)
    #print(tdoas)

    dd = TDOAs * soundSpeed 
    vals = dd / chanSpacing
    print("vals: ", vals)
    print("pi: ", np.pi / 2)
    
    if ((np.abs(vals) > 1).any()):
        print("Out of bounds values: ")
        print(vals)

    


    # Clip the array
    vals = np.clip(vals, min_val, max_val)
    print(vals)
    print(np.arcsin(vals) * 180 / np.pi)


vert = -.000666667
vert = 0.0006

tdoa = np.array([[0,0,0,0],[1,0,0,0],[2,1,0,0],[3,2,1,0]]) * vert
for ex in tdoa:
    print(ex)

# tdoa = [1 -> 2, 1 -> 3, 1 -> 4, 2 -> 3, 2 -> 4, 3 -> 4]
chanSpacing  = np.array([1, 2, 3, 1, 2, 1])
tdoas_flattened = np.array([1, 2, 3, 1, 2, 1]) * vert
my_calculate_doa(tdoas_flattened,1500, chanSpacing)


[0. 0. 0. 0.]
[0.0006 0.     0.     0.    ]
[0.0012 0.0006 0.     0.    ]
[0.0018 0.0012 0.0006 0.    ]
vals:  [0.9 0.9 0.9 0.9 0.9 0.9]
pi:  1.5707963267948966
[0.9 0.9 0.9 0.9 0.9 0.9]
[64.15806724 64.15806724 64.15806724 64.15806724 64.15806724 64.15806724]


In [27]:
dt = 0.00066666666666
dt = 0
v = 1500
dd = v * dt

np.arcsin(dd) * 180 / np.pi

0.0

In [46]:
aa = np.array([1,2,3,4,6,7,8,9])

print(aa.any() > 4)

False


In [48]:
(aa > 40).any()

False

In [55]:
np.arcsin(1.0000005)

/tmp/ipykernel_5299/1075070950.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(1.0000005)


nan

In [87]:
delay = 66 / 100000
dm = delay * 1500
np.arcsin(dm) * 180 / np.pi

81.89038554400581

In [88]:
1/1500

0.0006666666666666666

In [90]:
.0006666 * 100000

66.66000000000001